[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "neurology-gait-pose-kinematics"
version = "2.0.0"
description = "GaitMind-AI: 3D Video Pose Estimation & Parkinsonian Bradykinesia"
readme = "README.md"
authors = [{ name = "Dr. Abu Suraih Sakhri", email = "abusuraih@example.com" }]
license = { text = "MIT" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Security/Cryptography",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]
requires-python = ">=3.9"
dependencies = []

[project.scripts]
neurology-gait-pose-kinematics = "gait_mind_ai.cli:main"

[project.urls]
Homepage = "https://github.com/abusuraihsakhri/neurology-gait-pose-kinematics"
Repository = "https://github.com/abusuraihsakhri/neurology-gait-pose-kinematics.git"
